# Site settings
title: Meiosis
description: Meiosis is a type of cell division which reduces the chromosome number of the parent cell by half to form four haploid gametes
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://loganoneal.github.io/meiosis/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: Logan O'Neal
twitter: loganofneal
github:  loganoneal

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: loganoneal #github username
repo: meiosis #github repository
branch: master #branch
relative_source: ../meiosis/ #source directory
destination: ../meiosis-pages/ #destination directory
production_url: https://meiosis.loganoneal.com/
source_url:  https://meiosis.loganoneal.com/ #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml